# Generated by Django 3.1.1 on 2020-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('otheruser', 'OTHERUSER')], default='otheruser', max_length=50),
        ),
    ]
