# Generated by Django 3.1.1 on 2020-12-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='role',
        ),
    ]
